### PR TITLE
DEV: Use exec for IPython commands.

### PR DESCRIPTION
**Pull request by ssanderson**
This makes the SIGTERM sent by `docker stop` hit the correct process.

### CODE REVIEW

**Comment by ssanderson** [comment]
Looks like this doesn't actually work: it makes `docker stop` work correctly, but ipython notebook can't spawn kernels if it's been `exec`'ed.  I'm seeing that behavior outside of docker as well, so I'm guessing there's a bug in the interaction between IPython and `exec`

**Comment by rgbkrk** [comment]
:unamused:

**Comment by ssanderson** [comment]
@rgbkrk FYI, the note here regarding seeing weirdness with `exec` outside of docker turned out not to be true.

I'm working around this right now using more or less the solution described as Option 3 in https://github.com/ipython/docker-notebook/issues/38.

```
# Forward SIGINT AND SIGTERM
_forward_sigint(){
    echo "forwarding int"
    kill -SIGINT $NOTEBOOK_PID
}
_forward_sigterm(){
    echo "forwarding term"
    kill -SIGTERM $NOTEBOOK_PID
}
trap _forward_sigterm SIGTERM
trap _forward_sigint SIGINT

# Run notebook in the background so we can get its pid.
ipython notebook --no-browser --port 8888&

NOTEBOOK_PID=$!
wait $NOTEBOOK_PID
```

**Comment by Carreau** [comment]
Should we close this one?

**Comment by rgbkrk** [comment]
I'll leave that up to @ssanderson.

@parente has been using supervisord inside docker-stacks.

**Comment by parente** [comment]
@krallin recommended tini as a replacement for supervisord (https://github.com/jupyter/docker-stacks/issues/24#issuecomment-139322416) I plan to look into it soon for the docker-stacks.

**Comment by rgbkrk** [comment]
Closing since this has been in a WIP state for a while, re-open if we continue on with it.

**Comment by funkyfuture** [comment]
i'm using the notebook-image in a Docker Compose-setup on a local machine for data processing.
in this use-case this patch does help and i'd pledge to merge it.

**Comment by funkyfuture** [comment]
sorry, it took me a while to notice the kernel-issue.

**Pull request closed without merging**
